version: '3.9'

volumes:
  buckets:
    external: false

services:
  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: snickerdoodle
    ports:
      - 9001:9001
      - 9000:9000
    volumes:
      - buckets:/data
    command: server --console-address ":9001" /data